name: Code Quality

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for better analysis

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files --show-diff-on-failure

    - name: Check for security issues with bandit
      run: |
        pip install bandit
        bandit -r dtcc_wrapper_tetgen -ll -f json -o bandit-report.json || true
      continue-on-error: true

    - name: Upload bandit results
      uses: actions/upload-artifact@v4
      with:
        name: bandit-security-report
        path: bandit-report.json
      if: always()